# Generated by Django 3.2.3 on 2021-05-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=30, verbose_name='NOME USUARIO')),
                ('sobrenome_usuario', models.CharField(max_length=30, verbose_name='SOBRENOME USUARIO')),
                ('username', models.CharField(max_length=30, verbose_name='USERNAME')),
                ('senha_usuario', models.CharField(max_length=30)),
            ],
        ),
    ]
