# Generated by Django 3.2.3 on 2021-05-24 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0004_auto_20210524_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotousuarios',
            options={'verbose_name': 'fotos_Usuario', 'verbose_name_plural': 'fotos_Usuario'},
        ),
        migrations.AddField(
            model_name='fotousuarios',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='NOME DO USUARIO'),
            preserve_default=False,
        ),
    ]
